# Site
name: 'The ScrewUp'
description: 'The Home of The ScrewUp, where you get the best ways to do normal stuff.'
logo: 'assets/images/thescrewupsmall.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'donatetothescrewup@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Arvind:
      name:           Arvind
      site:           https://arvindvenkat.github.io/
      avatar:         "assets/images/avatar.jpg"
      bio:            "Hi, I am Arvind. I like my T shirt White and Coffee Black."
      email:          arvindvenkat17@gmail.com
      twitter:        https://twitter.com/arv_ven

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Arvind
      avatar: "assets/images/avatar.jpg"
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
