# Site
name: 'The ScrewUp'
description: 'The ScrewUp is the place you come to wipe off your tears and learn to manage your shit.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'donatetothescrewup@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    The ScrewUp:
      name:           The ScrewUp
      site:           https://www.arvindvenkat.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am The ScrewUp who started this off. Hope you find this useful."
      email:          donatetothescrewup@gmail.com
      twitter:        https://twitter.com/arv_ven

    
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]